# Generated by Django 4.0.6 on 2022-08-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('LocationS', models.CharField(blank=True, max_length=100, null=True)),
                ('Prices', models.FloatField(blank=True, null=True)),
                ('Offer', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('date_dep', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
