# Generated by Django 4.0.6 on 2022-08-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelo', '0002_travel_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
