# Generated by Django 4.0.6 on 2022-08-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelo', '0003_alter_travel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='Name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='Offer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
