# Generated by Django 4.0.6 on 2022-08-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelo', '0004_alter_travel_name_alter_travel_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='Offer',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
