# Generated by Django 4.0.6 on 2022-08-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelo', '0005_alter_travel_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='date_dep',
            field=models.DateField(blank=True, null=True),
        ),
    ]
