# Generated by Django 4.0.6 on 2022-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelo', '0006_alter_travel_date_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='date_dep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
