# Generated by Django 4.0.6 on 2022-08-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelo', '0007_alter_travel_date_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aero', models.CharField(blank=True, max_length=150, null=True)),
                ('heure_dep', models.TimeField(null=True)),
                ('heure_arr', models.TimeField(null=True)),
                ('diff', models.CharField(blank=True, max_length=100, null=True)),
                ('prices', models.FloatField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=1500, null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('dep', models.CharField(blank=True, max_length=150, null=True)),
                ('arr', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
