# Generated by Django 4.0.6 on 2022-08-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelo', '0009_reco'),
    ]

    operations = [
        migrations.AddField(
            model_name='reco',
            name='dest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reco',
            name='fm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reco',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
