# Generated by Django 4.0.6 on 2022-08-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travelo', '0010_reco_dest_reco_fm_alter_reco_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reco',
            old_name='location',
            new_name='iplocation',
        ),
    ]
