# Generated by Django 4.0.6 on 2022-09-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travelo', '0012_rename_dest_reco_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='historique',
            fields=[
                ('travel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Travelo.travel')),
                ('dated_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Travelo.travel',),
        ),
    ]
