# Generated by Django 4.0.6 on 2022-09-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelo', '0013_historique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='dated_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
